[workspace]
resolver = "2"
members = [
    "crates/qlexpress",
    "crates/qlexpress-derive",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "4.2.0-beta.1"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }