[workspace]
resolver = "2"
members = [
    "crates/qlexpress",
    "crates/qlexpress-derive",
    "crates/qlexpress-verification",
    "crates/qlexpress-process",
    "qlexpress-test",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/easy-4-rust/qlexpress-rust"
homepage = "https://github.com/easy-4-rust/qlexpress-rust"
rust-version = "1.85"
version = "0.1.0"

[workspace.metadata.qlexpress]
java-baseline-version = "4.2.0-beta"
java-baseline-commit = "9065b9ac5d985dcd02e627239aa9cdb78fb2f7f3"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
num-bigint = "0.4"
num-traits = "0.2"
regex = "1"
sha2 = "0.10"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
